// <auto-generated />
using System;
using CoopDesk.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoopDesk.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CoopDeskDbContext))]
    partial class CoopDeskDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("support")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoopDesk.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CollaboratorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CollaboratorId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", "support");

                    b.HasData(
                        new
                        {
                            Id = new Guid("40d30e39-4c09-4108-90f2-64895c8ae701"),
                            CreatedAtUtc = new DateTime(2026, 7, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@coopdesk.local",
                            FullName = "Administrador Demo",
                            IsActive = true,
                            PasswordHash = "PBKDF2$100000$BmILyUgJIjH4aZwOXR5ozA==$rOnI6VqfnVp51b9MaK7dA5myVY8P03lUFCicYddbN98=",
                            Role = "Administrator"
                        },
                        new
                        {
                            Id = new Guid("03c7b3fb-c8f2-4a4f-8b6d-070c2f738702"),
                            CollaboratorId = new Guid("fb7c7217-6d70-4a56-857e-bfdb87170c2e"),
                            CreatedAtUtc = new DateTime(2026, 7, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "atendente@coopdesk.local",
                            FullName = "Bruno Lima",
                            IsActive = true,
                            PasswordHash = "PBKDF2$100000$UToCSteUYZ2ZuMONaNTlvA==$OwHgBWAAwjySiIcl1by4wg4PtfyZGHUllBiwVgct2aA=",
                            Role = "Agent"
                        },
                        new
                        {
                            Id = new Guid("35e626a2-f4cc-4072-a2cd-a1437e255703"),
                            CollaboratorId = new Guid("a471f67e-03ab-4d81-a4cd-53b903a59e7f"),
                            CreatedAtUtc = new DateTime(2026, 7, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "solicitante@coopdesk.local",
                            FullName = "Carla Mendes",
                            IsActive = true,
                            PasswordHash = "PBKDF2$100000$JMPytRZJ0LrGtuWOXOrv/A==$2X7sRd5DlKsO98uSlJ19UtCBZ4DZAjiBrWdwQxg+JjA=",
                            Role = "Requester"
                        });
                });

            modelBuilder.Entity("CoopDesk.Domain.Entities.Collaborator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Collaborators", "support");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0dba1335-4389-4d47-bff5-8f2b27b5d901"),
                            CreatedAtUtc = new DateTime(2026, 7, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("534652fd-dffa-4d30-b270-ce46b0a46b0d"),
                            Email = "ana.souza@coopdesk.local",
                            FullName = "Ana Souza",
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("fb7c7217-6d70-4a56-857e-bfdb87170c2e"),
                            CreatedAtUtc = new DateTime(2026, 7, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("5d6ef6ef-5f87-47f4-8a8e-e35708e5e101"),
                            Email = "bruno.lima@coopdesk.local",
                            FullName = "Bruno Lima",
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("a471f67e-03ab-4d81-a4cd-53b903a59e7f"),
                            CreatedAtUtc = new DateTime(2026, 7, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("f6070747-ed08-4a7f-94d0-ddcc7851cb7f"),
                            Email = "carla.mendes@coopdesk.local",
                            FullName = "Carla Mendes",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("CoopDesk.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Departments", "support");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5d6ef6ef-5f87-47f4-8a8e-e35708e5e101"),
                            CreatedAtUtc = new DateTime(2026, 7, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Tecnologia"
                        },
                        new
                        {
                            Id = new Guid("534652fd-dffa-4d30-b270-ce46b0a46b0d"),
                            CreatedAtUtc = new DateTime(2026, 7, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Operacoes"
                        },
                        new
                        {
                            Id = new Guid("f6070747-ed08-4a7f-94d0-ddcc7851cb7f"),
                            CreatedAtUtc = new DateTime(2026, 7, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Credito"
                        });
                });

            modelBuilder.Entity("CoopDesk.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedAgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("DueAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("ProblemType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAgentId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Priority");

                    b.HasIndex("RequesterId");

                    b.HasIndex("Status");

                    b.ToTable("Tickets", "support");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e4fd358e-b413-4a3e-aa5d-419112995001"),
                            AssignedAgentId = new Guid("fb7c7217-6d70-4a56-857e-bfdb87170c2e"),
                            CreatedAtUtc = new DateTime(2026, 7, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("5d6ef6ef-5f87-47f4-8a8e-e35708e5e101"),
                            Description = "Tela legada apresenta timeout ao buscar propostas com muitas parcelas.",
                            DueAtUtc = new DateTime(2026, 7, 9, 12, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "High",
                            ProblemType = "SystemError",
                            RequesterId = new Guid("a471f67e-03ab-4d81-a4cd-53b903a59e7f"),
                            Status = "Open",
                            Title = "Falha ao consultar proposta de credito"
                        });
                });

            modelBuilder.Entity("CoopDesk.Domain.Entities.TicketHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketHistories", "support");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ce7a2365-62fc-40fd-b71e-60b809834001"),
                            CreatedAtUtc = new DateTime(2026, 7, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            NewStatus = "Open",
                            Notes = "Chamado aberto.",
                            OccurredAtUtc = new DateTime(2026, 7, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            PerformedBy = "seed",
                            TicketId = new Guid("e4fd358e-b413-4a3e-aa5d-419112995001")
                        });
                });

            modelBuilder.Entity("CoopDesk.Domain.Entities.AppUser", b =>
                {
                    b.HasOne("CoopDesk.Domain.Entities.Collaborator", "Collaborator")
                        .WithMany()
                        .HasForeignKey("CollaboratorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Collaborator");
                });

            modelBuilder.Entity("CoopDesk.Domain.Entities.Collaborator", b =>
                {
                    b.HasOne("CoopDesk.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CoopDesk.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("CoopDesk.Domain.Entities.Collaborator", "AssignedAgent")
                        .WithMany("AssignedTickets")
                        .HasForeignKey("AssignedAgentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CoopDesk.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoopDesk.Domain.Entities.Collaborator", "Requester")
                        .WithMany("RequestedTickets")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedAgent");

                    b.Navigation("Department");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("CoopDesk.Domain.Entities.TicketHistory", b =>
                {
                    b.HasOne("CoopDesk.Domain.Entities.Ticket", "Ticket")
                        .WithMany("History")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("CoopDesk.Domain.Entities.Collaborator", b =>
                {
                    b.Navigation("AssignedTickets");

                    b.Navigation("RequestedTickets");
                });

            modelBuilder.Entity("CoopDesk.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
